version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: MyHashPassword123
      POSTGRES_USER: db_user
      POSTGRES_DB: car_rental
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - car-rental-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JWT_SECRET: Heu9iDKdasnd9cjsGqYxHcTng9HjrLwOhTsCEGwDLoQ=
    container_name: car-rental-api
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgresql://db_user:MyHashPassword123@postgres:5432/car_rental?schema=public
      - JWT_SECRET=Heu9iDKdasnd9cjsGqYxHcTng9HjrLwOhTsCEGwDLoQ=
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - car-rental-network

volumes:
  pg_data:

networks:
  car-rental-network:
